### ISSUE TITLE
Remote seems to be out of date

### ISSUE THREAD

**Issue by igoracmelo** [guitld/Distortion-Bot-for-Telegram#1]
The actual bot (@DistortBot) is not sending the same messages that are written in `distortBot.py` file.

**Comment by guitld** [comment]
The username for this particular bot is actually @theDistortionBot, @DistortBot is a different one :)> The actual bot (@DistortBot) is not sending the same messages that are written in `distortBot.py` file.

**Comment by igorcmelo** [comment]
@guitld 
Got it. My bad.
